/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2019-10-12")
public class IsWeixinServerData implements org.apache.thrift.TBase<IsWeixinServerData, IsWeixinServerData._Fields>, java.io.Serializable, Cloneable, Comparable<IsWeixinServerData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("IsWeixinServerData");

  private static final org.apache.thrift.protocol.TField IS_SERVER_FIELD_DESC = new org.apache.thrift.protocol.TField("is_server", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField ECHOSTR_FIELD_DESC = new org.apache.thrift.protocol.TField("echostr", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new IsWeixinServerDataStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new IsWeixinServerDataTupleSchemeFactory();

  public boolean is_server; // required
  public java.lang.String echostr; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    IS_SERVER((short)1, "is_server"),
    ECHOSTR((short)2, "echostr");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // IS_SERVER
          return IS_SERVER;
        case 2: // ECHOSTR
          return ECHOSTR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __IS_SERVER_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.IS_SERVER, new org.apache.thrift.meta_data.FieldMetaData("is_server", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.ECHOSTR, new org.apache.thrift.meta_data.FieldMetaData("echostr", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(IsWeixinServerData.class, metaDataMap);
  }

  public IsWeixinServerData() {
  }

  public IsWeixinServerData(
    boolean is_server,
    java.lang.String echostr)
  {
    this();
    this.is_server = is_server;
    setIs_serverIsSet(true);
    this.echostr = echostr;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public IsWeixinServerData(IsWeixinServerData other) {
    __isset_bitfield = other.__isset_bitfield;
    this.is_server = other.is_server;
    if (other.isSetEchostr()) {
      this.echostr = other.echostr;
    }
  }

  public IsWeixinServerData deepCopy() {
    return new IsWeixinServerData(this);
  }

  @Override
  public void clear() {
    setIs_serverIsSet(false);
    this.is_server = false;
    this.echostr = null;
  }

  public boolean isIs_server() {
    return this.is_server;
  }

  public IsWeixinServerData setIs_server(boolean is_server) {
    this.is_server = is_server;
    setIs_serverIsSet(true);
    return this;
  }

  public void unsetIs_server() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __IS_SERVER_ISSET_ID);
  }

  /** Returns true if field is_server is set (has been assigned a value) and false otherwise */
  public boolean isSetIs_server() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __IS_SERVER_ISSET_ID);
  }

  public void setIs_serverIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __IS_SERVER_ISSET_ID, value);
  }

  public java.lang.String getEchostr() {
    return this.echostr;
  }

  public IsWeixinServerData setEchostr(java.lang.String echostr) {
    this.echostr = echostr;
    return this;
  }

  public void unsetEchostr() {
    this.echostr = null;
  }

  /** Returns true if field echostr is set (has been assigned a value) and false otherwise */
  public boolean isSetEchostr() {
    return this.echostr != null;
  }

  public void setEchostrIsSet(boolean value) {
    if (!value) {
      this.echostr = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case IS_SERVER:
      if (value == null) {
        unsetIs_server();
      } else {
        setIs_server((java.lang.Boolean)value);
      }
      break;

    case ECHOSTR:
      if (value == null) {
        unsetEchostr();
      } else {
        setEchostr((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case IS_SERVER:
      return isIs_server();

    case ECHOSTR:
      return getEchostr();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case IS_SERVER:
      return isSetIs_server();
    case ECHOSTR:
      return isSetEchostr();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof IsWeixinServerData)
      return this.equals((IsWeixinServerData)that);
    return false;
  }

  public boolean equals(IsWeixinServerData that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_is_server = true;
    boolean that_present_is_server = true;
    if (this_present_is_server || that_present_is_server) {
      if (!(this_present_is_server && that_present_is_server))
        return false;
      if (this.is_server != that.is_server)
        return false;
    }

    boolean this_present_echostr = true && this.isSetEchostr();
    boolean that_present_echostr = true && that.isSetEchostr();
    if (this_present_echostr || that_present_echostr) {
      if (!(this_present_echostr && that_present_echostr))
        return false;
      if (!this.echostr.equals(that.echostr))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((is_server) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetEchostr()) ? 131071 : 524287);
    if (isSetEchostr())
      hashCode = hashCode * 8191 + echostr.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(IsWeixinServerData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetIs_server()).compareTo(other.isSetIs_server());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIs_server()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.is_server, other.is_server);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetEchostr()).compareTo(other.isSetEchostr());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEchostr()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.echostr, other.echostr);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("IsWeixinServerData(");
    boolean first = true;

    sb.append("is_server:");
    sb.append(this.is_server);
    first = false;
    if (!first) sb.append(", ");
    sb.append("echostr:");
    if (this.echostr == null) {
      sb.append("null");
    } else {
      sb.append(this.echostr);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class IsWeixinServerDataStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public IsWeixinServerDataStandardScheme getScheme() {
      return new IsWeixinServerDataStandardScheme();
    }
  }

  private static class IsWeixinServerDataStandardScheme extends org.apache.thrift.scheme.StandardScheme<IsWeixinServerData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, IsWeixinServerData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // IS_SERVER
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.is_server = iprot.readBool();
              struct.setIs_serverIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ECHOSTR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.echostr = iprot.readString();
              struct.setEchostrIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, IsWeixinServerData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(IS_SERVER_FIELD_DESC);
      oprot.writeBool(struct.is_server);
      oprot.writeFieldEnd();
      if (struct.echostr != null) {
        oprot.writeFieldBegin(ECHOSTR_FIELD_DESC);
        oprot.writeString(struct.echostr);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class IsWeixinServerDataTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public IsWeixinServerDataTupleScheme getScheme() {
      return new IsWeixinServerDataTupleScheme();
    }
  }

  private static class IsWeixinServerDataTupleScheme extends org.apache.thrift.scheme.TupleScheme<IsWeixinServerData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, IsWeixinServerData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetIs_server()) {
        optionals.set(0);
      }
      if (struct.isSetEchostr()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetIs_server()) {
        oprot.writeBool(struct.is_server);
      }
      if (struct.isSetEchostr()) {
        oprot.writeString(struct.echostr);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, IsWeixinServerData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.is_server = iprot.readBool();
        struct.setIs_serverIsSet(true);
      }
      if (incoming.get(1)) {
        struct.echostr = iprot.readString();
        struct.setEchostrIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

